language: go
go:
  - "1.16"
before_install:
  - |
    sudo apt-get remove --purge elasticsearch -y &&
    curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.12.1-amd64.deb &&
    sudo dpkg -i --force-confnew elasticsearch-7.12.1-amd64.deb &&
    sudo systemctl restart elasticsearch
    journalctl -ru elasticsearch
install:
  - go get -t ./...
services:
  - elasticsearch
script:
  - |
    set -e
    go test -v -covermode=count -coverprofile=coverage.out ./...
    go get github.com/mattn/goveralls
    $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
